spring:
  profiles:
    active: dev

  application:
    name: credit-api

  datasource:
    url: jdbc:postgresql://localhost:5432/creditdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-password-or-app-token
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  messages:
    basename: i18n/messages

  aws:
    s3:
      access-key: your-aws-access-key
      secret-key: your-aws-secret-key
      region: us-east-1
      bucket: your-s3-bucket-name

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500, expireAfterAccess=30m

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.creditapi: DEBUG

invoice:
  provider:
    type: tiranota
    tiranota:
      base-url: https://api.tiranota.com.br
      api-key: ${TIRANOTA_API_KEY}
      timeout: 3000

jwt:
  secret: 7130e0b9e8f74c28c92ae5ad6bd9d9a678f8e78561a937ef04728f5d79ec3d6b
  access-token-ttl: 15m
  refresh-token-ttl: 30d

social:
  google:
    client-id: YOUR_GOOGLE_CLIENT_ID
    client-secret: ${GOOGLE_CLIENT_SECRET}
  facebook:
    app-id: YOUR_FACEBOOK_APP_ID
    app-secret: ${FACEBOOK_APP_SECRET}

resilience4j:
  ratelimiter:
    instances:
      authService:
        limit-refresh-period: 30s
        limit-for-period: 10
      emailService:
        limit-refresh-period: 1m
        limit-for-period: 3
      userService:
        limit-refresh-period: 30s
        limit-for-period: 10

  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 500ms

  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
        max-wait-duration: 0

app:
  frontend:
    reset-password-url: https://app.seudominio.com/reset-password?token=
  cdn:
    avatar-base-url: https://cdn.seudominio.com/